name: crelat_venv_gpu_support
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aiodns=3.5.0=py313h06a4308_1
  - aiohappyeyeballs=2.6.1=py313h06a4308_0
  - aiohttp=3.13.2=py313hee96239_0
  - aiosignal=1.4.0=py313h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - arrow-cpp=21.0.0=h4e7ead5_0
  - attrs=25.4.0=py313h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - binutils_impl_linux-64=2.40=h5293946_0
  - binutils_linux-64=2.40.0=hc2dff05_2
  - blas=1.0=openblas
  - bottleneck=1.4.2=py313haa0f9ac_1
  - brotlicffi=1.1.0.0=py313hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - click=8.2.1=py313h06a4308_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cuda-cccl_linux-64=12.4.127=h06a4308_2
  - cuda-crt-dev_linux-64=12.4.131=h06a4308_0
  - cuda-crt-tools=12.4.131=h06a4308_0
  - cuda-cudart=12.4.127=h99ab3db_0
  - cuda-cudart-dev=12.4.127=h99ab3db_0
  - cuda-cudart-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart-static=12.4.127=h99ab3db_0
  - cuda-cudart-static_linux-64=12.4.127=hd681fbe_0
  - cuda-cudart_linux-64=12.4.127=hd681fbe_0
  - cuda-cuobjdump=12.4.127=h6a678d5_1
  - cuda-cupti=12.4.127=h6a678d5_1
  - cuda-driver-dev_linux-64=12.4.127=hd681fbe_0
  - cuda-nvcc=12.4.131=h02f8991_0
  - cuda-nvcc-dev_linux-64=12.4.131=h4ee8466_0
  - cuda-nvcc-impl=12.4.131=h99ab3db_0
  - cuda-nvcc-tools=12.4.131=h99ab3db_0
  - cuda-nvcc_linux-64=12.4.131=he92618c_0
  - cuda-nvdisasm=12.4.127=h6a678d5_1
  - cuda-nvrtc=12.4.127=h99ab3db_1
  - cuda-nvtx=12.4.127=h6a678d5_1
  - cuda-nvvm-dev_linux-64=12.4.131=h06a4308_0
  - cuda-nvvm-impl=12.4.131=h6a678d5_0
  - cuda-nvvm-tools=12.4.131=h6a678d5_0
  - cuda-version=12.4=hbda6634_3
  - cudnn=9.1.1.17=cuda12_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - datasets=3.3.2=py313h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - dbus=1.16.2=h5bd4931_0
  - dill=0.3.8=py313h06a4308_0
  - expat=2.7.3=h3385a95_0
  - filelock=3.20.0=py313h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py313hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py313hbdd6827_0
  - fsspec=2024.12.0=py313h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_2
  - gensim=4.4.0=py313hbdd6827_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - glog=0.5.0=h6a678d5_1
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py313h5eee18b_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_2
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.1.8=py313h84c0859_0
  - huggingface_hub=0.34.4=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - importlib-metadata=8.5.0=py313h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - jansson=2.14=h5eee18b_1
  - jinja2=3.1.6=py313h06a4308_0
  - joblib=1.5.2=py313h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - kiwisolver=1.4.8=py313h6a678d5_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h0131e85_1
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcublas=12.4.5.8=h99ab3db_1
  - libcufft=11.2.1.3=h99ab3db_1
  - libcups=2.4.2=h252cb56_2
  - libcurand=10.3.5.147=h99ab3db_1
  - libcurl=8.16.0=heebcbe5_0
  - libcusolver=11.6.1.9=h99ab3db_1
  - libcusparse=12.3.1.170=h99ab3db_1
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libglib=2.84.4=h77a78f3_0
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm14=14.0.6=hecde1de_4
  - libllvm19=19.1.7=h465586c_5
  - libmlir19=19.1.7=hfbf14b3_2
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libnvjitlink=12.4.127=h99ab3db_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.15.0=hd8eb582_4
  - libtiff=4.7.0=hde9077f_0
  - libtorch=2.6.0=gpu_cuda124_h81cafb7_206
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lit=20.1.8=py313h06a4308_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - magma=2.7.1=h9153a54_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.6=py313h06a4308_1
  - matplotlib-base=3.10.6=py313h4948728_1
  - mkl=2025.0.0=hacee8c2_941
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py313h06a4308_0
  - multidict=6.7.0=py313hee96239_0
  - multiprocess=0.70.15=py313h06a4308_0
  - mysql=8.4.0=h721767e_2
  - nccl=2.21.5.1=ha515578_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.5=py313h06a4308_0
  - nltk=3.9.2=py313hf83b21e_0
  - nomkl=3.0=0
  - numexpr=2.14.1=py313ha5a4a6c_0
  - numpy=2.3.4=py313h816806e_1
  - numpy-base=2.3.4=py313h7203c5b_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - opentelemetry-api=1.37.0=py313h06a4308_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pcre2=10.46=hf426167_0
  - pillow=12.0.0=py313h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - ply=3.11=py313h06a4308_1
  - propcache=0.3.1=py313h5eee18b_0
  - protobuf=5.29.3=py313he621ea3_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=21.0.0=py313h23c847b_0
  - pycares=4.10.0=py313ha137689_0
  - pycparser=2.23=py313h06a4308_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=5.15.10=py313h6a678d5_1
  - pyqt5-sip=12.13.0=py313h5eee18b_1
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=1_cp313
  - pytorch=2.6.0=gpu_cuda124_py313hf27f713_206
  - pytorch-gpu=2.6.0=gpu_cuda124_h1234567_206
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.2=py313h5eee18b_0
  - qt-main=5.15.2=hb6262e9_12
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - regex=2025.9.1=py313hee96239_0
  - requests=2.32.5=py313h06a4308_1
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.6.2=py313h498d7c9_0
  - scikit-learn=1.7.2=py313h23c847b_0
  - scipy=1.16.3=py313he2bc341_0
  - seaborn=0.13.2=py313h06a4308_3
  - setuptools=80.9.0=py313h06a4308_0
  - sip=6.7.12=py313h6a678d5_1
  - six=1.17.0=py313h06a4308_0
  - sleef=3.5.1=h5eee18b_2
  - smart_open=7.3.1=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sqlite=3.51.0=h2a70700_0
  - sympy=1.14.0=py313h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.21.0=py313hb8e4a85_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_1
  - transformers=4.49.0=py313h06a4308_0
  - triton=3.1.0=cuda124py313hac27663_3
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py312h939ff40_1
  - wheel=0.45.1=py313h06a4308_0
  - wrapt=1.17.0=py313h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py313hee96239_0
  - zipp=3.21.0=py313h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /gpfs0/bgu-vilenchi/users/morari/env/crelat_venv_gpu_support
